name: Bug Report Form
description: Create a report to help us improve by reporting a bug.
title: "[Bug]: "
labels: 
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: e.g., email@example.com
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Please describe the bug you encountered.
      placeholder: Describe the bug here.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug.
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Describe the expected behavior here.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add screenshots to help explain the bug.
  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: Select the type of device where the issue occurred.
      options:
        - Desktop
        - Mobile
        - Tablet
      default: 0
    validations:
      required: true
  - type: dropdown
    id: desktop-info
    attributes:
      label: Desktop Information
      description: Provide information about your desktop environment.
      options:
        - iOS
        - Windows
        - macOS
        - Linux
  - type: dropdown
    id: smartphone-info
    attributes:
      label: Smartphone Information
      description: Provide information about your smartphone environment.
      options:
        - iPhone
        - Android
  - type: dropdown
    id: tablet-info
    attributes:
      label: Tablet Information
      description: Provide information about your tablet environment.
      options:
        - iPad
        - Android Tablet
  - type: dropdown
    id: browser-info
    attributes:
      label: Browser Information
      description: Provide information about your browser.
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
        - Opera
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any additional context about the bug.
      placeholder: Add additional context here.
    validations:
      required: false  
